dbAddr: "localhost:5432"
dbName: "weather_subscription"
dbUser: "postgres"
dbPass: "postgres"
serverPort: "8080"
weather_api:
  key: "your-key-here"
email:
  local:
    from: "noreply@weather-subscription.com"
    smtpHost: "localhost"
    smtpPort: "1025"
  production:
    from: "${EMAIL_FROM}"
    password: "${EMAIL_PASSWORD}"
    smtpHost: "${EMAIL_SMTP_HOST}"
    smtpPort: "${EMAIL_SMTP_PORT}"