/*
 * Weather API
 *
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY  
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarineHour struct {
	TimeEpoch int32 `json:"time_epoch,omitempty"`
	Time string `json:"time,omitempty"`
	TempC float64 `json:"temp_c,omitempty"`
	TempF float64 `json:"temp_f,omitempty"`
	IsDay int32 `json:"is_day,omitempty"`
	Condition *ForecastCondition `json:"condition,omitempty"`
	WindMph float64 `json:"wind_mph,omitempty"`
	WindKph float64 `json:"wind_kph,omitempty"`
	WindDegree float64 `json:"wind_degree,omitempty"`
	WindDir string `json:"wind_dir,omitempty"`
	PressureMb float64 `json:"pressure_mb,omitempty"`
	PressureIn float64 `json:"pressure_in,omitempty"`
	PrecipMm float64 `json:"precip_mm,omitempty"`
	PrecipIn float64 `json:"precip_in,omitempty"`
	Humidity float64 `json:"humidity,omitempty"`
	Cloud float64 `json:"cloud,omitempty"`
	FeelslikeC float64 `json:"feelslike_c,omitempty"`
	FeelslikeF float64 `json:"feelslike_f,omitempty"`
	WindchillC float64 `json:"windchill_c,omitempty"`
	WindchillF float64 `json:"windchill_f,omitempty"`
	HeatindexC float64 `json:"heatindex_c,omitempty"`
	HeatindexF float64 `json:"heatindex_f,omitempty"`
	DewpointC float64 `json:"dewpoint_c,omitempty"`
	DewpointF float64 `json:"dewpoint_f,omitempty"`
	WillItRain int32 `json:"will_it_rain,omitempty"`
	ChanceOfRain float64 `json:"chance_of_rain,omitempty"`
	WillItSnow int32 `json:"will_it_snow,omitempty"`
	ChanceOfSnow float64 `json:"chance_of_snow,omitempty"`
	VisKm float64 `json:"vis_km,omitempty"`
	VisMiles float64 `json:"vis_miles,omitempty"`
	GustMph float64 `json:"gust_mph,omitempty"`
	GustKph float64 `json:"gust_kph,omitempty"`
	SigHtMt float64 `json:"sig_ht_mt,omitempty"`
	SwellHtMt float64 `json:"swell_ht_mt,omitempty"`
	SwellHtFt float64 `json:"swell_ht_ft,omitempty"`
	SwellDir float64 `json:"swell_dir,omitempty"`
	SwellDir16Point float64 `json:"swell_dir_16_point,omitempty"`
	SwellPeriodSecs float64 `json:"swell_period_secs,omitempty"`
	Uv int32 `json:"uv,omitempty"`
}
